##
## config/application_settings.yml
##
##
default: &default
  oauth:
    google:
      applicatoin_id: XXXXXXXXXXXXXXXXX
      application_secret: XXXXXXXXXXXXXXXXX
   admin:
    name: "admin"
    email: "XXXXXXX@gmail.com"
    password: "XXXXXXXX"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
